global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@polaris-synapse.com'
  smtp_auth_username: 'alerts@polaris-synapse.com'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    repeat_interval: 5m
  - match:
      service: compliance
    receiver: 'compliance-alerts'
    group_wait: 0s
    repeat_interval: 1m
  - match:
      service: risk-management
    receiver: 'risk-alerts'
    group_wait: 5s
    repeat_interval: 10m

receivers:
- name: 'default'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#polaris-alerts'
    title: 'Polaris Synapse Alert'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Service:* {{ .Labels.service }}
      {{ end }}

- name: 'critical-alerts'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#polaris-critical'
    title: '🚨 CRITICAL: Polaris Synapse Alert'
    text: |
      {{ range .Alerts }}
      *CRITICAL ALERT:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Service:* {{ .Labels.service }}
      *Time:* {{ .StartsAt }}
      {{ end }}
  email_configs:
  - to: 'oncall@polaris-synapse.com'
    subject: '🚨 CRITICAL: Polaris Synapse Alert'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Severity: {{ .Labels.severity }}
      Started: {{ .StartsAt }}
      {{ end }}
  pagerduty_configs:
  - routing_key: '${PAGERDUTY_INTEGRATION_KEY}'
    description: '{{ .GroupLabels.alertname }}: {{ .Annotations.summary }}'

- name: 'compliance-alerts'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#polaris-compliance'
    title: '⚖️ COMPLIANCE: Polaris Synapse Alert'
    text: |
      {{ range .Alerts }}
      *COMPLIANCE ALERT:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Immediate Action Required*
      {{ end }}
  email_configs:
  - to: 'compliance@polaris-synapse.com'
    subject: '⚖️ COMPLIANCE ALERT: Immediate Action Required'
    body: |
      {{ range .Alerts }}
      COMPLIANCE VIOLATION DETECTED
      
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Time: {{ .StartsAt }}
      
      This requires immediate investigation and response.
      {{ end }}

- name: 'risk-alerts'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#polaris-risk'
    title: '⚠️ RISK: Polaris Synapse Alert'
    text: |
      {{ range .Alerts }}
      *RISK ALERT:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Service:* {{ .Labels.service }}
      {{ end }}
  email_configs:
  - to: 'risk@polaris-synapse.com'
    subject: '⚠️ RISK ALERT: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Risk Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Time: {{ .StartsAt }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']