# Development Configuration for Polaris Synapse
# Tony Stark's Crypto Trading System

environment: development

# Kafka Configuration
kafka:
  brokers: "localhost:9092"
  topics:
    market_data_raw: "market_data.raw"
    market_data_normalized: "market_data.normalized"
    sentiment_analyzed: "sentiment.analyzed"
    onchain_events: "onchain.events"
    orders_client: "orders.client"
    orders_incoming: "orders.incoming"
    orders_validated: "orders.validated"
    orders_executable: "orders.executable"
    orders_matched: "orders.matched"
    fills: "fills"
    trading_decisions: "trading.decisions"
    compliance_alerts: "compliance.alerts"
    system_heartbeats: "system.heartbeats"
    transactions_all: "transactions.all"
  
  consumer_groups:
    market_data_handler: "market-data-handler-group"
    order_gateway: "order-gateway-group"
    risk_manager: "risk-manager-group"
    execution_engine: "execution-engine-group"
    order_matching_engine: "order-matching-engine-group"
    llm_agents: "llm-agents-group"
    compliance_gateway: "compliance-gateway-group"

# Database Configuration
databases:
  orders:
    url: "postgresql://matcher:matchpass@localhost:5432/orderdb"
    max_connections: 20
    min_connections: 5
  
  compliance:
    url: "postgresql://compliance:compliancepass@localhost:5432/compliancedb"
    max_connections: 15
    min_connections: 3
  
  analytics:
    url: "postgresql://analytics:analyticspass@localhost:5432/analyticsdb"
    max_connections: 10
    min_connections: 2

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  database: 0
  password: ""
  max_connections: 20

# Exchange Configuration
exchanges:
  binance:
    enabled: true
    api_key: "${BINANCE_API_KEY}"
    api_secret: "${BINANCE_API_SECRET}"
    endpoint: "wss://stream.binance.com:9443/ws"
    rate_limit: 1200  # requests per minute
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "SOLUSDT"
      - "ADAUSDT"
      - "DOTUSDT"
  
  coinbase:
    enabled: true
    api_key: "${COINBASE_API_KEY}"
    api_secret: "${COINBASE_API_SECRET}"
    endpoint: "wss://ws-feed.pro.coinbase.com"
    rate_limit: 600
    symbols:
      - "BTC-USD"
      - "ETH-USD"
      - "SOL-USD"
      - "ADA-USD"
      - "DOT-USD"

# Blockchain Configuration
blockchains:
  ethereum:
    enabled: true
    rpc_url: "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
    firehose_endpoint: "firehose-ethereum:13042"
    contracts:
      - address: "0xA0b86a33E6441b8C4505E2E2E5B3E3B3E3B3E3B3"
        name: "USDC"
      - address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        name: "USDT"
  
  solana:
    enabled: true
    rpc_url: "https://api.mainnet-beta.solana.com"
    websocket_url: "wss://api.mainnet-beta.solana.com"
    programs:
      - address: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"
        name: "Jupiter"
      - address: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
        name: "Raydium"

# LLM Configuration
llm:
  providers:
    openai:
      enabled: true
      api_key: "${OPENAI_API_KEY}"
      model: "gpt-4-turbo-preview"
      max_tokens: 4000
      temperature: 0.7
      rate_limit: 3500  # tokens per minute
    
    anthropic:
      enabled: false
      api_key: "${ANTHROPIC_API_KEY}"
      model: "claude-3-opus-20240229"
      max_tokens: 4000
      temperature: 0.7
  
  agents:
    fact_agent:
      weight: 0.6
      confidence_threshold: 0.5
      technical_indicators:
        - "sma_5"
        - "sma_20"
        - "rsi_14"
        - "macd"
        - "bollinger_bands"
    
    subjectivity_agent:
      weight: 0.4
      confidence_threshold: 0.5
      sentiment_sources:
        - "twitter"
        - "reddit"
        - "news"
        - "onchain"
    
    risk_agent:
      sharpe_threshold: 1.2
      max_drawdown: 0.05
      position_limits:
        "BTC/USD": 50000
        "ETH/USD": 25000
        "SOL/USD": 10000

# Risk Management
risk:
  global:
    max_portfolio_risk: 0.02  # 2% of portfolio
    max_position_size: 0.1    # 10% of portfolio
    max_correlation: 0.7
    stop_loss: 0.05           # 5% stop loss
    take_profit: 0.15         # 15% take profit
  
  per_symbol:
    "BTC/USD":
      max_position: 50000
      max_daily_volume: 100000
      volatility_limit: 0.8
    "ETH/USD":
      max_position: 25000
      max_daily_volume: 75000
      volatility_limit: 0.9

# Compliance Configuration
compliance:
  kyc:
    required_level: "basic"
    enhanced_threshold: 10000  # USD
    verification_providers:
      - "jumio"
      - "onfido"
  
  aml:
    transaction_monitoring: true
    sanctions_screening: true
    pep_screening: true
    adverse_media_screening: true
    
    thresholds:
      large_transaction: 10000
      suspicious_velocity: 10  # transactions per hour
      daily_limit: 100000
      risk_score_threshold: 75
    
    rules:
      - name: "Large Transaction"
        type: "amount"
        threshold: 10000
        enabled: true
      - name: "Velocity Check"
        type: "velocity"
        max_per_hour: 10
        enabled: true
      - name: "Unusual Hours"
        type: "time"
        start_hour: 22
        end_hour: 6
        enabled: true

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
    scrape_interval: "15s"
  
  grafana:
    enabled: true
    port: 3000
    admin_password: "${GRAFANA_ADMIN_PASSWORD}"
  
  alerts:
    slack_webhook: "${SLACK_WEBHOOK_URL}"
    email_smtp: "smtp.gmail.com:587"
    email_from: "alerts@polaris-synapse.com"
  
  metrics:
    latency_buckets: [0.001, 0.01, 0.1, 1.0, 10.0]
    retention_days: 30

# Logging Configuration
logging:
  level: "info"
  format: "json"
  outputs:
    - "stdout"
    - "file:/var/log/polaris-synapse/app.log"
  
  structured: true
  include_caller: true
  include_stacktrace: false

# Security Configuration
security:
  api_keys:
    enabled: true
    rotation_days: 90
  
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    burst_size: 100
  
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_days: 30
  
  tls:
    enabled: true
    cert_path: "/etc/ssl/certs/polaris-synapse.crt"
    key_path: "/etc/ssl/private/polaris-synapse.key"

# Performance Configuration
performance:
  kafka:
    batch_size: 1000
    linger_ms: 5
    compression_type: "snappy"
  
  database:
    connection_timeout: 30
    query_timeout: 60
    statement_cache_size: 100
  
  cache:
    ttl_seconds: 300
    max_size: 10000
  
  circuit_breaker:
    failure_threshold: 5
    timeout_seconds: 60
    reset_timeout_seconds: 300

# Feature Flags
features:
  sentiment_analysis: true
  onchain_analysis: true
  multi_exchange: true
  paper_trading: true
  backtesting: true
  real_trading: false  # Disabled in development
  compliance_gateway: true
  risk_management: true
  llm_agents: true